1️⃣ Holiday Management
Create a table for storing public holidays:

CREATE TABLE PUBLIC_HOLIDAYS (
    holiday_date DATE PRIMARY KEY,
    description VARCHAR2(100)
);


INSERT INTO PUBLIC_HOLIDAYS (holiday_date, description)
VALUES (TO_DATE('2025-12-25','YYYY-MM-DD'), 'Christmas');

INSERT INTO PUBLIC_HOLIDAYS (holiday_date, description)
VALUES (TO_DATE('2026-01-01','YYYY-MM-DD'), 'New Year');


2️⃣ Audit Log Table

Create a centralized table to track DML attempts:

CREATE TABLE AUDIT_LOG (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    username VARCHAR2(30),
    operation_type VARCHAR2(10),
    table_name VARCHAR2(30),
    status VARCHAR2(10),
    remarks VARCHAR2(200)
);

3️⃣ Audit Logging Function

Function to insert audit records:

CREATE OR REPLACE PROCEDURE log_audit(
    p_table_name  IN VARCHAR2,
    p_operation   IN VARCHAR2,
    p_status      IN VARCHAR2,
    p_remarks     IN VARCHAR2
)
IS
BEGIN
    INSERT INTO AUDIT_LOG(username, table_name, operation_type, status, remarks)
    VALUES (USER, p_table_name, p_operation, p_status, p_remarks);
END;
/

4️⃣ Restriction Check Function

Function to enforce weekday and public holiday restrictions

CREATE OR REPLACE FUNCTION check_restriction
RETURN BOOLEAN
IS
    v_today DATE := TRUNC(SYSDATE);
    v_count NUMBER;
BEGIN
    -- Check weekday (Monday=2, ..., Friday=6)
    IF TO_CHAR(v_today,'D','NLS_DATE_LANGUAGE=ENGLISH') BETWEEN '2' AND '6' THEN
        RETURN FALSE;
    END IF;

    -- Check public holiday
    SELECT COUNT(*) INTO v_count
    FROM PUBLIC_HOLIDAYS
    WHERE holiday_date = v_today;

    IF v_count > 0 THEN
        RETURN FALSE;
    END IF;

    RETURN TRUE;  -- Allowed (weekend & not holiday)
END;
/

5️⃣ Simple Trigger Example

Trigger to prevent INSERTs on restricted days:

CREATE OR REPLACE TRIGGER trg_restrict_sale
BEFORE INSERT OR UPDATE OR DELETE ON SALE
FOR EACH ROW
DECLARE
    v_allowed BOOLEAN;
BEGIN
    v_allowed := check_restriction;

    IF NOT v_allowed THEN
        log_audit('SALE', ORA_SYSEVENT, 'DENIED', 'Operation not allowed on weekday/holiday');
        RAISE_APPLICATION_ERROR(-20001, 'DML operations not allowed on weekdays or public holidays.');
    ELSE
        log_audit('SALE', ORA_SYSEVENT, 'ALLOWED', 'Operation permitted.');
    END IF;
END;
/

6️⃣ Compound Trigger (Optional Advanced Version)

If you want row-level and statement-level auditing together:

CREATE OR REPLACE TRIGGER trg_compound_sale
FOR INSERT OR UPDATE OR DELETE ON SALE
COMPOUND TRIGGER

    -- Statement-level variable
    v_total_attempts NUMBER := 0;

    BEFORE STATEMENT IS
    BEGIN
        v_total_attempts := 0;
    END BEFORE STATEMENT;

    BEFORE EACH ROW IS
        v_allowed BOOLEAN;
    BEGIN
        v_total_attempts := v_total_attempts + 1;
        v_allowed := check_restriction;
        IF NOT v_allowed THEN
            log_audit('SALE', ORA_SYSEVENT, 'DENIED', 'Row-level restriction violated');
            RAISE_APPLICATION_ERROR(-20001, 'DML operations not allowed on weekdays or holidays.');
        ELSE
            log_audit('SALE', ORA_SYSEVENT, 'ALLOWED', 'Row-level operation permitted');
        END IF;
    END BEFORE EACH ROW;

    AFTER STATEMENT IS
    BEGIN
        DBMS_OUTPUT.PUT_LINE(v_total_attempts || ' rows attempted for DML operation.');
    END AFTER STATEMENT;

END trg_compound_sale;
/

7️⃣ Testing Scenarios

BEGIN
    INSERT INTO SALE(sale_id, customer_id, product_id, region_id, quantity, total_amount)
    VALUES (30001, 1, 101, 1, 2, 2000);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/


